export const RULE_ID = 'K-04';
export const MAX_URLS_TO_CHECK = 20;
export const LOW_SIGNAL_CONTAINER_SELECTOR =
  'header, nav, [role="navigation"], [class*="breadcrumb"], [aria-label*="breadcrumb"], [class*="pagination"], [class*="sort"], [class*="filter"], [class*="menu"]';
export const SUPPLEMENTAL_ZONE_SELECTOR =
  'aside, footer, [class*="recommend"], [class*="related"], [class*="suggest"], [class*="sidebar"], [class*="upsell"], [class*="widget"]';
export const IMPORTANT_KEYWORDS = [
  'terms',
  'privacy',
  'cookie',
  'cookies',
  'return',
  'returns',
  'refund',
  'refunds',
  'exchange',
  'warranty',
  'support',
  'help',
  'customer service',
  'service',
  'contact',
  'about',
  'shipping',
  'delivery',
  'track',
  'tracking',
  'order',
  'policy',
  'policies',
  'legal',
  'faq',
  'questions',
  'delete',
  'cancel',
  'unsubscribe',
  'billing',
  'payment',
  'checkout',
  'cart',
  'register',
  'registration',
  'sign up',
  'sign in',
  'login',
  'account',
  'settings',
  'profile',
  'subscription',
  'manage subscription',
  'accessibility',
  'security',
  'complaint',
  'complaints',
  'gdpr'
] as const;
